services:
  core_db:
    image: postgres:16
    container_name: core_db
    environment:
      POSTGRES_DB: core_db
      POSTGRES_USER: core_user
      POSTGRES_PASSWORD: core_pass
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U core_user -d core_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  taxi_db:
    image: postgres:16
    container_name: taxi_db
    environment:
      POSTGRES_DB: taxi_db
      POSTGRES_USER: taxi_user
      POSTGRES_PASSWORD: taxi_pass
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taxi_user -d taxi_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  ai_db:
    image: pgvector/pgvector:pg16
    container_name: ai_db
    environment:
      POSTGRES_DB: ai_db
      POSTGRES_USER: ai_user
      POSTGRES_PASSWORD: ai_pass
    ports:
      - "5436:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ai_user -d ai_db"]
      interval: 5s
      timeout: 5s
      retries: 10